---
title: "rand_forest"
author: "ZZ"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float:
      collapsed: no
      smooth_scroll: no
---

```{r setup}
knitr::opts_chunk$set(message = F,warning = F)
```

```{r}
library(tidyverse)
library(stringr)
library(randomForest)
library(knitr)
```


# data
```{r}
d_c <- read.delim('./mono/20191228/chlamy_dilu2_2.txt',header = T, skip = 1, dec = ',')
#d_c <- read.delim('./mono/20191223/chlamy.txt',header = T, skip = 1, dec = ',')
d_c2 <- read.delim('./mono/20191228/chlamy_undilu.txt',header = T, skip = 1, dec = ',')
d_c <- d_c %>% bind_rows(d_c2)
samples <- sample(1:nrow(d_c), nrow(d_c)*0.05)
d_c_test <- d_c %>% 
  slice(samples)
d_c_train <- d_c %>% 
  slice(-samples)


d_chlo <- read.delim('./mono/20191228/chlorella_dilu2.txt',header = T, skip = 1, dec = ',')
#d_chlo <- read.delim('./mono/20191223/chlorella.txt',header = T, skip = 1, dec = ',')
d_chlo2 <- read.delim('./mono/20191228/chlorella_undilu.txt',header = T, skip = 1, dec = ',')
d_chlo <- d_chlo %>% bind_rows(d_chlo2)
samples <- sample(1:nrow(d_chlo), nrow(d_chlo)*0.5)
d_chlo_test <- d_chlo %>% 
  slice(samples)
d_chlo_train <- d_chlo %>% 
  slice(-samples)

d_13 <- read.delim('./mono/20191228/13_undilu.txt',header = T, skip = 1, dec = ',')
samples <- sample(1:nrow(d_13), nrow(d_13)*0.25)
d_13_test <- d_13 %>% 
  slice(samples)
d_13_train <- d_13 %>% 
  slice(-samples)

d_76 <- read.delim('./mono/20191228/76_undilu.txt',header = T, skip = 1, dec = ',')
d_762 <- read.delim('./mono/20191228/76_dilu2.txt',header = T, skip = 1, dec = ',')
d_76 <- d_76 %>% bind_rows(d_762)
# d_chlo <- rbind(d_76,d_762)%>% 
#   slice(sample(2000,2000))
samples <- sample(1:nrow(d_76), nrow(d_76)*0.25)
d_76_test <- d_76 %>% 
  slice(samples)
d_76_train <- d_76 %>% 
  slice(-samples)

```



```{r}
build_train <- function(data_chlamy = d_c_train, data_comp = d_chlo_train){
  data_chlamy <- data_chlamy %>% 
    mutate(sp = 'chlamy')
  data_comp <- data_comp %>% 
    mutate(sp = 'sp_comp')
  data <- data_chlamy %>% 
    bind_rows(data_comp) %>% 
    dplyr::select(colnames(data_chlamy)[grep('[0-9]{2}',colnames(data_chlamy))], sp) %>% # which columns to select
    dplyr::select(-one_of(colnames(data_chlamy)[grep('Bkgd|Flow|Time',colnames(data_chlamy))])) %>% # which colums to remove
    mutate(sp = as.factor(sp))
  return(data)
}
```








# Chlamy Chlorella mix

```{r}
c_chlo_1_9 <- read.delim('./bi/c65_1_9.txt',header = T, skip = 1, dec = ',') %>% 
  mutate(volum_c = 1, volum_comp = 9)
c_chlo_9_1 <- read.delim('./bi/c65_9_1.txt',header = T, skip = 1, dec = ',') %>% 
  mutate(volum_c = 9, volum_comp = 1)
c_chlo_99_1 <- read.delim('./bi/c65_99_1.txt',header = T, skip = 1, dec = ',') %>% 
  mutate(volum_c = 99, volum_comp = 1)
c_chlo_1_99 <- read.delim('./bi/c65_1_99.txt',header = T, skip = 1, dec = ',') %>% 
  mutate(volum_c = 1, volum_comp = 99)
c_chlo <- rbind(c_chlo_1_9, c_chlo_9_1, c_chlo_99_1, c_chlo_1_99) %>% 
  mutate(sp = 65)
```


```{r}
train <- build_train()

rf <- randomForest(
  sp ~ .,
  ntree = 1000,
  data = train
)
rf
```


top 10 preditors
```{r}
importance(rf) %>%
  as.data.frame() %>%
  rownames_to_column('var') %>%
  mutate(MeanDecreaseGini = round(MeanDecreaseGini,3)) %>% 
  arrange(-MeanDecreaseGini) %>% 
  head(10)
```



```{r}
c_chlo$pre_sp <- predict(rf, newdata=c_chlo)
```



```{r}

t_density <- function(data = c_chlo){
  table <-data %>% group_by(volum_c, volum_comp, pre_sp,sp) %>% tally() %>% 
    spread(pre_sp, n) %>% 
    mutate(density_c = chlamy/(chlamy +sp_comp)) %>% 
    dplyr::select(volum_c, volum_comp, sp, density_c)
  return(table)
}

```

## use test data from the monoculture
```{r}

test <- d_c_test %>% 
  mutate(sp = 'chlamy') %>% 
  bind_rows(d_chlo_test %>% mutate(sp = 'sp_comp'))

test$sp_pred <- predict(rf, newdata=test %>% select(-sp))
print('accuracy')
sum(test$sp == as.character(test$sp_pred))/nrow(test)
sum(test$sp_pred =='chlamy')/nrow(test)

```



# chlamy Synechococcus mix

```{r}
train <- build_train(data_comp = d_76_train)

rf <- randomForest(
  sp ~ .,
  data = train
)
rf
```


top 10 preditors
```{r}
importance(rf) %>%
  as.data.frame() %>%
  rownames_to_column('var') %>%
  mutate(MeanDecreaseGini = round(MeanDecreaseGini,3)) %>% 
  arrange(-MeanDecreaseGini) %>% 
  head(10)
```

```{r}
c_76_9_1 <- read.delim('./bi/c76_9_1.txt',header = T, skip = 1, dec = ',') %>% 
  mutate(volum_c = 9, volum_comp = 1, sp = 76)
c_76_9_1$pre_sp <- predict(rf, newdata=c_76_9_1)

```


## use test data from the monoculture
```{r}

test <- d_c_test %>% 
  mutate(sp = 'chlamy') %>% 
  bind_rows(d_76_test %>% mutate(sp = 'sp_comp'))
test$sp_pred <- predict(rf, newdata=test %>% select(-sp))
print('accuracy')
sum(test$sp == as.character(test$sp_pred))/nrow(test)
sum(as.character(test$sp_pred)=='sp_comp')/nrow(test)
```

# Chlamy Scenedesmus obliquus mix
```{r}
c_13_1_9 <- read.delim('./bi/c13_mix_1_9.txt',header = T, skip = 1, dec = ',') %>% 
  mutate(volum_c = 1, volum_comp = 9, sp = 13)
  
c_13_1_99 <- read.delim('./bi/c13_mix_1_99.txt',header = T, skip = 1, dec = ',')%>% 
  mutate(volum_c = 1, volum_comp = 99, sp = 13)
c_13_9_1 <- read.delim('./bi/c13_mix_9_1.txt',header = T, skip = 1, dec = ',')%>% 
  mutate(volum_c = 9, volum_comp = 1, sp = 13)
c_13_99_1 <- read.delim('./bi/c13_mix_99_1.txt',header = T, skip = 1, dec = ',')%>% 
  mutate(volum_c = 99, volum_comp = 1, sp = 13)
c_13 <- rbind(c_13_1_9, c_13_1_99, c_13_9_1, c_13_99_1)
```

model
```{r}
train <- build_train(data_comp = d_13_test)

rf <- randomForest(
  sp ~ .,
  data = train
)
rf

```

top 10 preditors
```{r}
importance(rf) %>%
  as.data.frame() %>%
  rownames_to_column('var') %>%
  mutate(MeanDecreaseGini = round(MeanDecreaseGini,3)) %>% 
  arrange(-MeanDecreaseGini) %>% 
  head(10)
```


```{r}
c_13$pre_sp <- predict(rf, newdata = c_13)

```

## use test data from the monoculture
```{r}
test <- d_c_test %>% 
  mutate(sp = 'chlamy') %>% 
  bind_rows(d_13_test %>% mutate(sp = 'sp_comp'))
test$sp_pred <- predict(rf, newdata=test)
print('accuracy')
sum(test$sp == as.character(test$sp_pred))/nrow(test)

```

# density table
```{r}
density <- read.delim('./mono/20191228/density.txt', dec = ',')
```


```{r}
colnames(density) <- c('lab','density','X')
d_bi <- density %>% 
  dplyr::select( - X) %>% 
  slice(grep('mix',lab)) %>% 
  mutate(lab = sub('.daf', '', lab)) %>% 
  separate('lab', into = c('combi','type','volum_c', 'volum_comp', 'id'),sep = '_') %>% 
  mutate(volum_c = as.numeric(volum_c),
         volum_comp  = as.numeric(volum_comp),
         density = density/ 10^6) %>% 
  mutate(volum_ratio_c = volum_c / (volum_c + volum_comp)) %>% 
  mutate(sp_comp  = stringr::str_extract(combi, '[0-9]{2}'))
# d_mono <- density %>% 
#   dplyr::select( - X) %>% 
#   slice(-grep('mix',lab)) %>% 
#   mutate(lab = sub('.daf', '', lab)) %>% 
#   mutate(sp_comp  = stringr::str_extract(lab, '[0-9]{2}'))
d_mono <- data.frame(sp = c('c', '65', '76', '13'),
                     density_mono = c(1, 6, 21, 2.08))

d_bi_expect <- d_bi %>% 
  mutate(c_orig = 1) %>% 
  left_join(d_mono, by = c('sp_comp' = 'sp')) %>% 
  rename(comp_orig = density_mono) %>% 
  mutate(expect_c = c_orig * volum_ratio_c,
         expect_comp = comp_orig * (1-volum_ratio_c),
         expect_density = expect_c + expect_comp,
         expected_den_ratio_c = expect_c/expect_density) %>% 
  dplyr::select(sp_comp, volum_c, volum_comp, volum_ratio_c, expected_den_ratio_c)
  

```


due to the error rate, density will be overestimated when low (e.g. rows 2 & 5) 
```{r}
t_count <- rbind(
t_density(c_chlo),
t_density(c_76_9_1),
t_density(c_13))

d_compare <- d_bi_expect %>% 
  left_join(t_count %>% mutate(sp_comp = as.character(sp))) %>% 
  dplyr::select(-c(sp, volum_c, volum_comp)) %>% 
  mutate(sp_comp = ifelse(sp_comp == '13', 'Scenedesmus',
                          ifelse(sp_comp == '65', 'Chlorella', 'Synechococcus'))) %>% 
  rename(species = sp_comp,
         ratio_Chlamy_volume = volum_ratio_c,
         ratio_Chlamy_density_expected = expected_den_ratio_c,
         ratio_Chlamy_density_caclulated = density_c
         )
d_compare %>% kable(digits = 3)

```

```{r, eval =F}
d_compare %>% 
  gather('type', 'ratio', - c(sp_comp, volum_ratio_c)) %>%
  ggplot() + aes( x = volum_ratio_c, y = ratio, col = type) + geom_point() + facet_wrap(~ sp_comp)
```


